#!/bin/bash

set -e

cd $(dirname -- "$0")
mkdir -p ../build
cd ../build
cmake \
    -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
    -DCMAKE_BUILD_TYPE=Debug \
    ../src
cmake --build . -- -j3
./geometry
